# Generated by Django 5.2 on 2025-07-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('cold', 'Cold Beverages'), ('snack', 'Snacks'), ('dessert', 'Desserts')], default='coffee', max_length=20),
        ),
    ]
